language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - uname -a
  - npm i html-pdf -g
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version

before_script:
  - git clone --recursive https://github.com/cssandstuff/hugo-theme-winning.git themes/winning

script:
  - hugo --theme=winning
  - cp themes/winning/exampleSite/generatepdf.js generatepdf.js
  - node generatepdf.js

after_success:
  - cd ./public
  - echo alongwy.top > CNAME
  - git init
  - git config --global user.name "Along"
  - git config --global user.email "15939423778@163.com"
  - git add .
  - git commit -m "Update Index Pages"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - index
env:
 global:
   - GH_REF: github.com/AlongWY/AlongWY.github.io.git
